### ISSUE TITLE
JS-Controller 4.0 Beta Testing Checklist

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1707]
- [x] Fix Alpha findings
- [X] Update "legacy testing" to be compatible with jsonl default-DB
- [x] Send out PRs for Legacy Testing Repos
- [x] Update testing library to be compatible with jsonl default-DB (Dependabot will bring out updates
- [x] Communication to developers about testing lib update!
- [x] Add Admin Notification once we reached organic limits
- [x] Finally merge linked tickets
- [x] Update Changelog and Communication for Beta Testing

**Comment by Apollon77** [comment]
Admin 5.3.0 has the two Admin topics solved
