### ISSUE TITLE
[Tracking] Restrict object/state names to not contain ",", "?", "[" and "]" and " and ' and Space

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#198]
To ease support of objects in Redis and to avoid other problems we decided to not allow certain characters (",", "?", "[" and "]" and " and ' and spaces).

In https://forum.iobroker.net/viewtopic.php?f=36&t=13700&e=1&view=unread#p145069 we currently collect all known adapters that currently generate such object IDs, they need to get fixed.

These are for now:

- [ ]  Smartmeter-Adapter, (v1.2.0 auf GitHub hats schon gefixt, aber alle betroffenen States werden neu anlegt)
- [x]  UPNP Adapter
- [ ]  harmony (einmal gesehen bisher das ein State mit * da war)
- [x]  spotify-premium (je nachdem welche Zeichen alles in Playlist-Namen drin sind)
- [x]  hm-rpc bei Heizungsgruppen oder Rauchmeldergruppen
- [ ]  mikrotik
- [ ]  systeminfo

**Comment by Apollon77** [comment]
Idea @GermanBluefox : Make Regex with invalid characters available to adapter instance so that an adapter developer can use this to replace all invalid defined characters. What you think?

**Comment by twonky4** [comment]
Fixed in ioBroker.spotify-premium.

I used:
```
v.replace(/[,?[\]]+/g, '');
```

**Comment by Apollon77** [comment]
Can you use the regex from the check script please?! Think it also contains “ and ‘

**Comment by Apollon77** [comment]
Sorry forgot that we added more chars to the check script for reason ... will fix this in the issues later.

**Comment by Apollon77** [comment]
https://forum.iobroker.net/viewtopic.php?f=20&t=14645 ... nächste Runde: Jetzt Adapter Forum, hoffentlich kommen ein paar weitere Rückmeldungen

**Comment by GermanBluefox** [comment]
```
const FORBIDDEN_CHARS = /[\]\[*,;'"`<>\\\s?]/g;
```

**Comment by Apollon77** [comment]
In Testscript we had with last update:

/[ \*\?\[\]"']+/

Also kommen jetzt noch dazu: ,;`<>

Korrekt?

**Comment by Hypnos3** [comment]
Fehlt da nicht noch der Backslash "\"?

**Comment by Apollon77** [comment]
Wie ich es überblicke sind das die ersten zwei Backslashe der drei vor dem s :)

**Comment by Hypnos3** [comment]
genau ;) - der fehlte in deinem Post - den hast du jetzt ja nachgetragen.

**Comment by Apollon77** [comment]
For documentation: We allowed spaces again because too many adapters are affected by this ...

And we decided to replacing forbidden characters in adapter-class AND output an warning to log when we replace something. That way developer can see and will be contacted by the users.

Only effect from this is that adapter scripts think states have different names - is unimportant except "on(stateChange/objectChange) is using these new masked ids ... there things may break!!

**Comment by chefkoch009** [comment]
Update of iobroker.knx adapter was released. The signs according to this issue will be eleminated in _id.

**Comment by Apollon77** [comment]
Thank you.

**Comment by Apollon77** [comment]
I will close here ...

js-controller 1.4.2 which removed "*" is already in stable, 1.50 (see #215 ) changed behaviour by silently replacing invalid characters by "_" and will include a warn message.
In fact state ids will change, yes, and this will be communicated.

Adapter will only have problems when they also subscribe to changes for these startes because then they could get unexpected names ... this will then be reported by the users and needs to be fixed in adapters.

**Comment by hacki11** [comment]
What about [RIGHT SINGLE QUOTATION MARK' (U+2019)](https://www.fileformat.info/info/unicode/char/2019/index.htm)? Any issues here?

**Comment by Apollon77** [comment]
@hacki11 What is the question and why asking in an 2 years closed issue? ;-)

**Comment by hacki11** [comment]
I was asking if this character is also invalid somehow regarding this issue

**Comment by Apollon77** [comment]
regarding this 2 years old issue it is allowed ... but in js.controller 3.2 we will be a bit more strict ... thats basically the new definition going forward https://github.com/ioBroker/ioBroker.js-controller/pull/1115/files#diff-7f88797c7db38a6af7a3283e3af30f2cdd3c2489bd9c85a7a25b32ec2485f724R36
