### ISSUE TITLE
[Tracking] js-controller 1.4.2 for stable

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#214]
Current Stable: 1.2.3 (November 2017)
The following tasks needs to be done to get js-controller 1.42 to stable

Preparations:
- [x] Version out for a while and people using it
- [x] move hm-rpc 1.7.2 to stable (1.7.2 latest release 12.06.18)
- [x] move hm-rega 1.7.1 to stable (fixes https://github.com/ioBroker/ioBroker.hm-rega/issues/32 (Update hm-rega additional to hm-rpc to fill in the new named states)
- [x] move upnp 0.3.8 to stable
- [x] release and move smartmeter 1.2.0 to stable
- [x] move spotify-premium 0.3.1 to stable (@twonky4 )
- [x] build, release and bring to stable new zwave version (@AlCalzone , @Apollon77)
- [x] move miktotik 1.0.2 to stable
- [x] move harmony 0.9.1/3 https://github.com/Pmant/ioBroker.harmony/issues/25 to stable
- [x] (optional) release and move to stable sql, history, influxdb updates currently tested
- [x] combine important things from release-notes to send to all in a forum post?

Release it:
- [x] update version in stable repo
- [x] flag 1.4.2 as stable in npm dist-tag (last thing to do on release day)

Important:
- as character *  in state-ids was disallowed by this version, state creations get an error and are not created

Known Problems:

**Comment by twonky4** [comment]
With "move spotify-premium 0.3.1 to stable", do you want me to move it to version 1.0.0 or change the version for ioBroker.repositories/sources-dist-stable.json to 0.3.1?

**Comment by Apollon77** [comment]
> Are you talking about zwave 1.1.0 or the one currently on github? I guess the latter.
A version with the fixed replacement. I only check and it seemed to me that after that one commit no release was done

**Comment by AlCalzone** [comment]
I'll see if I can get that done tonight (except for the release on npm)

**Comment by Apollon77** [comment]
Thank you!

**Comment by AlCalzone** [comment]
And should we try to resolve #209 first?

**Comment by Apollon77** [comment]
history, sql and influxdb are with new versions on stable that support Aloas-Logging in order to continue logging on same ID as before pot. replacements. So should help here.

**Comment by Apollon77** [comment]
Stable merge for smartmeter and some others planned for this weekend. hm-rpc basically also ok, For hm-rega test-feedback is missing. I asked in forum again.
mikrotik, harmony needs to be moved to stable, zwave still missing.

After that it's just "collecting the details" and then we are ready

**Comment by Apollon77** [comment]
I had forgotten this: 1.4.2 has one "issue". If adapter defines instanceobjects with empty id (used to create the basic adapter-instance object) then this is reported as "setObject id missing on adapter start.
We need to list this in known issues or such

**Comment by Apollon77** [comment]
only a new zwave version is needed and we need to move all above versions into stable too

ANd in fact we still have no proof that the hm-rega changes worked :-(

**Comment by AlCalzone** [comment]
ZWave is at 1.2.0 as of [now](https://github.com/ioBroker/ioBroker.zwave/commit/d62207c0e385a561c1e824951bb94882121cbd86). I can't release it on npm though.

**Comment by Apollon77** [comment]
js-controller 1-4-2 is featured in c't for end of next week I think.
Only thig left is to push some adapters in stable, or !?

**Comment by AlCalzone** [comment]
Regarding zwave: ioBroker/ioBroker.repositories#148

**Comment by Apollon77** [comment]
All other adapters above were also moved to stable with https://github.com/ioBroker/ioBroker.repositories/commit/c2f07b644fac3d52f7f08f49a307b7d6f852adfb

**Comment by Apollon77** [comment]
So, todos left:
[ ] combine important things from release-notes to send to all in a forum post?
[ ] update js-controller version in stable repo
[ ] flag 1.4.2 as stable via npm dist-tag (last thing to do on release day)

For infos:
As character * in state-ids was disallowed by this version, state creations get an error and are not created. Maybe also "teaser" that with 1.5.0 more characters are forbidden ...

**Comment by Apollon77** [comment]
Released to stable already
