### ISSUE TITLE
[Tracking] js-controller 1.5.x for latest

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#215]
js-controller 1.5.0 is upcoming, so as soon as #214 is done we could move 1.5.x to latest.
This ticket tries to track needed todos before this!

- [x] Sync https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/objects/objectsInMemServer.js#L102 to full list of characters? (in addition to replacing in adapter class), or sufficient this way? Or now remove the replace regex in objectsInMemServer.js#L102 again?
- [x] Add warning logging in js-controller as soon as forbidden characters are replaced so that this is visible. Log Message should say "Send this to the Developer: The following statte id contained invalid characters that were replaced. ${id} Please make sure invalid characters are replaced in adapter directly!"
- [x] ??Create an GitHub Issue for all Adapters informing the developer about this upcoming change? OR simply bring to latest and let user find the places where it makes problems? it will be mainly adapters with invalid Ids that now are replaces automatically AND that subscribe to changes for their own objects/states and receive unexpected names
- [x] Collect all the changes that we want tio bring in changelog ... these will be many :-) - see https://github.com/ioBroker/ioBroker.js-controller/issues/215#issuecomment-420070655
- [x] Communicate and bring to latest
...

**Comment by AlCalzone** [comment]
> Do we want to officially declae nodejs 4 as unsupported with this version?

I'd like this. This means we can finally start using ES6 classes
```js
class Foo extends Bar {
    // ...
}
```
instead of the weird ES5 constructs
```js
function Foo(options) {
    if (!(this instanceof Foo)) return new Foo(options);
    // ...
}
util.inherits(Foo, Bar);
```

**Comment by Apollon77** [comment]
:-)
The other thing is if we really break it in 1.5.0 ... but we just _officially_ communicate it

**Comment by AlCalzone** [comment]
Although breaking changes of this magnitude should be a v2.x (according to semver).

**Comment by Apollon77** [comment]
Then maybe 1.5.0 declare it officially "deprecated" and as soon as we have breaking stuff -> 2.0

**Comment by AlCalzone** [comment]
Why not make it deprecated in the upcoming stable 1.4.2 (1.4.3?) then?

**Comment by GermanBluefox** [comment]
1.4.2 ist schon längst da. Und publisched. Und ich habe kein label 1 4.2

пт, 22 июн. 2018 г., 15:14 AlCalzone <notifications@github.com>:

**Comment by GermanBluefox** [comment]
> Do we want to officially declae nodejs 4 as unsupported with this version?

First from 2.0.0

**Comment by Apollon77** [comment]
Here is my proposal for changelog:

**Breaking changes:**
* (bluefox) Breaking changes: "][*,;'"`<>\?" are no more allowed in IDs

**Feature changes:**
* (bluefox) the user by changing of states and objects is logged
* (bluefox) install specific version of missing adapter
* (bluefox) add disk info
* (bluefox) add memAvailable state
* (bluefox) add noChmod experimental settings
* (bluefox) stop instances only if they belongs to current host
* (bluefox) delete adapter only on current host and leave it on others
* (bluefox) Combine States and Objects (#203)
* (bluefox) Implement adapter.terminate('Because I need it') (#197)
* (alcalzone) add restart, disable, updateConfig methods to Adapter class
* (bluefox) add reinstall.js
* (bluefox) add "iob" as shortcut
* (bluefox) add getInterfaces to sendToHost
* (bluefox) implement backup of data folders via dataFolder flag
* (alcalzone) Add a wrapper method to safely expose ES6 classes to legacy code
* (bluefox) add information if instance is alive in "list instances"
* (stabilostick) added 'pidusage' for information about cpu and new states per adapter instance
* (bluefox) support of new mime types: pdf, doc, xls, ppt
* (bluefox) implement flag common.eraseOnUpload
* (bluefox) set quality codes on connection lost and adapter disconnect
* (alcalzone) Give adapters a chance to handle their own uncaught errors 
* (alcalzone) Add call stack information to hard to trace error logs
* (bluefox) add pattern2RegEx to tools

**Fixes and Optimizations:**
* (apollon77) the node10 testing was added
* (bluefox) the read file function was protected
* (bluefox) possible access rights problem was closed
* (bluefox) refactoring of memory calculations
* (bluefox) set default values of states by creation of new instances
* (alcalzone) Fix "install npm" messages, upgrade node typings to v6 
* (bluefox) check if mem file could be read
* (buzzy1337) fix calculation of kilobyte to megabyte and fix reading /proc/meminfo 
* (bluefox) Fix: Access to log files through admin does not work
* (bluefox) fix redis disconnect
* (bluefox) Update acme to V2 (#199)
* (bluefox) Improve deleteDevice (#186)
* (bluefox) fix cookie expiration
* (alcalzone) several async and testing fixes
* (bluefox) timeout for npm check added
* (bluefox) fix "object chmod 777 777 javascript.0.*" command
* (bluefox) do not send ready second time on reconnect db
* (Apollon77, Bluefox) prevent defaultObj to be overwritten with normal common details
* (bluefox) fix error if ID is empty
* (bluefox) check id by setObject
* (apollon77) Add amazon-dash to list of adapter to be installed with unsafe-perm
* (bluefox) leave backitup enabled after restore

**Comment by Apollon77** [comment]
Ok, german Forum-User-friendly summary.

---
js-controller 1.5.0 bringt neben zahlreichen Verbesserungen, Optimierungen und Fehlerbehebungen folgende Änderungen:
* Ab sofort sind die folgende Zeichen in Objekt-IDs verboten: ][*,;'"`<>?  Diese Zeichen werden automatisch durch Unterstriche ersetzt und es wird eine Warnung geloggt. Falls solch eine Warnung im Log zu finden ist bitte an den entsprechenden Adapter-Entwickler melden, sodass dieser den Adapter entsprechend anpassen kann. In Objekt-Namen sind diese Zeichen weiterhin erlaubt!
* Wenn Adapter automatisch nachinstalliert werden, wird die im gewählten Repository definierte Version installiert und nicht wie bisher die Latest Version.
* Unter system.adapter.* und system.host.* sind neue Informative States hinzugekommen die noch besser über Speicherberbrauch, CPU-Verbrauch oder verfügbaren Disk-Platz Auskunft geben. Diese Daten können zur Performance- und Fehlersuche genutzt werden und sind  im Admin bei der Nutzung des Expertenmodus unter Objekte sichtbar.
* reinstall.sh wurde durch reinstall.js ersetzt.
* Für Kommandozeilenaktionen kann jetzt auch die kürzere Variante "iob" verwendet werden
* Wenn Adapter die Verbindung zu den Gerätern verlieren (info.connection State geht auf false) dann werden alle Adapter-State-Werte mit dem korrekten Quality-Flag gekennzeichnet.

Wie immer gilt: Bei Problemen bitte im Forum melden und Issues im GitHub anlegen.

**Comment by AlCalzone** [comment]
Zusätzliche Infos für Adapter-Entwickler:
* Adapter bekommen jetzt die Möglichkeit, ihre eigenen unbehandelten Fehler zu behandeln. Dazu gibt es neben `"ready"` und co. ein neues Event `"error"`, welches die Fehlermeldung empfängt:
```js
const adapter = new utils.Adapter({
  ready: () => { /* ... */ },
  // ...
  error: (err) => {
    // Fehler behandeln und true zurückgeben, wenn der Fehler behoben wurde.
    // Der Adapter wird dann nicht neu gestartet!
    return true;
  }
}
```
* Es wurden vereinfachte Funktionen zur Adapter-Selbstverwaltung hinzugefügt, die ohne Anpassen der Konfigurationsobjekte auskommen:
  * Adapter neustarten: `adapter.restart()`
  * Adapter stoppen und deaktivieren: `adapter.disable()`
  * Adapterkonfiguration anpassen: `adapter.updateConfig(newConfig)`. `newConfig` ist ein Objekt mit dem zu aktualisierenden Teil der Konfiguration. Es muss nicht die vollständige Konfiguration übergeben werden.

**Comment by AlCalzone** [comment]
Für folgende Punkte wäre Dokumentation für Entwickler sinnvoll, erschließt sich mir aber nicht aus dem Kontext:
* common.eraseOnUpload - Was macht das?
* Deaktivierung des Adapters per `process.exit(...)` Was ist der ExitCode hierfür?
* add pattern2RegEx to tools könnte für Adapter-Entwickler interessant sein. Doku?

**Comment by AlCalzone** [comment]
Generell sollten wir zusehen, dass Änderungen, die Entwickler und Anwender betreffen, irgendwo vernünftig dokumentiert sind. Am besten geht das denke ich per Issue, in dem das kurz niedergeschrieben wird, oder im Falle eines PR im Erklärungstext:
* Was ist das Problem?
* Was wurde geändert?
* Was muss beachtet werden, bzw. wie wird es genutzt?

**Comment by Apollon77** [comment]
Sobald wir die neue Webseite haben wird das alles einfacher (und wir müssen disziplinierter arbeiten)

**Comment by Apollon77** [comment]
Ok, @GermanBluefox please check das obige sowohl von mir für Endkunden wie auch das von AlCalzone für Adapter Entwickler.

Wenn das passt (und die Vermutung von AlCalzone korrekt ist) dann wären wir bereit für latest mit der 1.5.0.

**Comment by Apollon77** [comment]
https://github.com/ioBroker/ioBroker.js-controller/releases/tag/1.5.0
